import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const MANTINE_ROOT = path.resolve(__dirname, "../../mantine/packages/@docs/demos/src");
export const MANTINE_DEMO_BASE = path.join(MANTINE_ROOT, "demos");
export const DEST_ROOT = path.resolve(__dirname, "../../app/src/component");

export const CORE_DATA = [
  {
    category: "Layout",
    pages: [
      "Container",
      "Center",
      "Group",
      "Stack",
      "AspectRatio",
      "AppShell",
      "SimpleGrid",
      "Grid",
      "Space",
      "Flex",
    ],
  },
  {
    category: "Inputs",
    pages: [
      "Input",
      "ColorPicker",
      "NativeSelect",
      "SegmentedControl",
      "Slider",
      "RangeSlider",
      "Switch",
      "TextInput",
      "Checkbox",
      "Radio",
      "Fieldset",
      "PinInput",
      "Chip",
      "Rating",
      "Textarea",
      "JsonInput",
      "PasswordInput",
      "FileInput",
      "ColorInput",
      "NumberInput",
      "AngleSlider",
    ],
  },
  {
    category: "Combobox",
    pages: ["Combobox", "Pill", "PillsInput", "Autocomplete", "TagsInput", "Select", "MultiSelect"],
  },
  {
    category: "Buttons",
    pages: ["ActionIcon", "Button", "CloseButton", "CopyButton", "FileButton", "UnstyledButton"],
  },
  {
    category: "Navigation",
    pages: [
      "Anchor",
      "Tabs",
      "Breadcrumbs",
      "Burger",
      "Pagination",
      "Stepper",
      "NavLink",
      "TableOfContents",
      "Tree",
    ],
  },
  {
    category: "Feedback",
    pages: [
      "Loader",
      "Alert",
      "Notification",
      "Skeleton",
      "Progress",
      "RingProgress",
      "SemiCircleProgress",
    ],
  },
  {
    category: "Overlays",
    pages: [
      "Popover",
      "Tooltip",
      "Overlay",
      "Affix",
      "Modal",
      "Drawer",
      "HoverCard",
      "Menu",
      "LoadingOverlay",
      "Dialog",
      "FloatingIndicator",
    ],
  },
  {
    category: "Data display",
    pages: [
      "BackgroundImage",
      "ColorSwatch",
      "Kbd",
      "Badge",
      "Avatar",
      "Accordion",
      "Indicator",
      "Card",
      "Image",
      "ThemeIcon",
      "Timeline",
      "Spoiler",
      "NumberFormatter",
    ],
  },
  {
    category: "Typography",
    pages: [
      "Blockquote",
      "Code",
      "Highlight",
      "Mark",
      "Table",
      "Text",
      "Title",
      "Typography",
      "List",
    ],
  },
  {
    category: "Miscellaneous",
    pages: [
      "Collapse",
      "FocusTrap",
      "Paper",
      "Portal",
      "ScrollArea",
      "Transition",
      "VisuallyHidden",
      "Divider",
      "Box",
    ],
  },
];

export const EXT_DATA = [
  {
    category: "Dates",
    pages: [
      "MiniCalendar",
      "Calendar",
      "DateTimePicker",
      "DatePicker",
      "DatePickerInput",
      "DateInput",
      "MonthPicker",
      "MonthPickerInput",
      "YearPicker",
      "YearPickerInput",
      "TimeInput",
      "TimePicker",
      "TimeGrid",
      "TimeValue",
    ],
  },
  {
    category: "Charts",
    pages: [
      "AreaChart",
      "BarChart",
      "LineChart",
      "CompositeChart",
      "DonutChart",
      "PieChart",
      "FunnelChart",
      "RadarChart",
      "ScatterChart",
      "BubbleChart",
      "RadialBarChart",
      "Sparkline",
      "Heatmap",
    ],
  },
  {
    category: "Schedule",
    pages: [
      "Schedule",
      "DayView",
      "MonthView",
      "WeekView",
      "YearView",
      "MobileMonthView",
      "RecurringEventsSchedule",
    ],
  },
  {
    category: "Other extensions",
    pages: [
      "CodeHighlight",
      "Notifications",
      "Spotlight",
      "Carousel",
      "Dropzone",
      "Nprogress",
      "Modals",
      "TipTap",
    ],
  },
];
