version: "3"

tasks:
  default:
    cmds:
      - pnpm dev
    dir: ./app

  app:*:
    vars:
      SCRIPTS: "{{index .MATCH 0}}"
    cmds:
      - pnpm {{.SCRIPTS}}
    dir: ./app

  copy-demos:
    cmds:
      - pnpm script:copy-demos

  mantinex-demo:*:
    vars:
      SCRIPTS: "{{index .MATCH 0}}"
    cmds:
      - pnpm --filter @mantinex/demo {{.SCRIPTS}}
      - cmd: pnpm install
        if: '{{eq .SCRIPTS "build"}}'

  tweak-mantine:*:
    vars:
      SCRIPTS: "{{index .MATCH 0}}"
    cmds:
      - pnpm --filter tweak-mantine {{.SCRIPTS}}

  build-all:
    cmds:
      - task: tweak-mantine:build
      - task: mantinex-demo:build
