export const groceries = [
  "🍎 Apples",
  "🍌 Bananas",
  "🥦 Broccoli",
  "🥕 Carrots",
  "🍫 Chocolate",
  "🍇 Grapes",
  "🍋 Lemon",
  "🥬 Lettuce",
  "🍄 Mushrooms",
  "🍊 Oranges",
  "🥔 Potatoes",
  "🍅 Tomatoes",
  "🥚 Eggs",
  "🥛 Milk",
  "🍞 Bread",
  "🍗 Chicken",
  "🍔 Hamburger",
  "🧀 Cheese",
  "🥩 Steak",
  "🍟 French Fries",
  "🍕 Pizza",
  "🥦 Cauliflower",
  "🥜 Peanuts",
  "🍦 Ice Cream",
  "🍯 Honey",
  "🥖 Baguette",
  "🍣 Sushi",
  "🥝 Kiwi",
  "🍓 Strawberries",
];
