/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtIndexRouteImport } from './routes/ext/index'
import { Route as CoreIndexRouteImport } from './routes/core/index'
import { Route as ExtElementNameRouteImport } from './routes/ext/$elementName'
import { Route as CoreElementNameRouteImport } from './routes/core/$elementName'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtIndexRoute = ExtIndexRouteImport.update({
  id: '/ext/',
  path: '/ext/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreIndexRoute = CoreIndexRouteImport.update({
  id: '/core/',
  path: '/core/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtElementNameRoute = ExtElementNameRouteImport.update({
  id: '/ext/$elementName',
  path: '/ext/$elementName',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreElementNameRoute = CoreElementNameRouteImport.update({
  id: '/core/$elementName',
  path: '/core/$elementName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/core/$elementName': typeof CoreElementNameRoute
  '/ext/$elementName': typeof ExtElementNameRoute
  '/core/': typeof CoreIndexRoute
  '/ext/': typeof ExtIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/core/$elementName': typeof CoreElementNameRoute
  '/ext/$elementName': typeof ExtElementNameRoute
  '/core': typeof CoreIndexRoute
  '/ext': typeof ExtIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/core/$elementName': typeof CoreElementNameRoute
  '/ext/$elementName': typeof ExtElementNameRoute
  '/core/': typeof CoreIndexRoute
  '/ext/': typeof ExtIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/core/$elementName'
    | '/ext/$elementName'
    | '/core/'
    | '/ext/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/core/$elementName'
    | '/ext/$elementName'
    | '/core'
    | '/ext'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/core/$elementName'
    | '/ext/$elementName'
    | '/core/'
    | '/ext/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  CoreElementNameRoute: typeof CoreElementNameRoute
  ExtElementNameRoute: typeof ExtElementNameRoute
  CoreIndexRoute: typeof CoreIndexRoute
  ExtIndexRoute: typeof ExtIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ext/': {
      id: '/ext/'
      path: '/ext'
      fullPath: '/ext/'
      preLoaderRoute: typeof ExtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/': {
      id: '/core/'
      path: '/core'
      fullPath: '/core/'
      preLoaderRoute: typeof CoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ext/$elementName': {
      id: '/ext/$elementName'
      path: '/ext/$elementName'
      fullPath: '/ext/$elementName'
      preLoaderRoute: typeof ExtElementNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/$elementName': {
      id: '/core/$elementName'
      path: '/core/$elementName'
      fullPath: '/core/$elementName'
      preLoaderRoute: typeof CoreElementNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  CoreElementNameRoute: CoreElementNameRoute,
  ExtElementNameRoute: ExtElementNameRoute,
  CoreIndexRoute: CoreIndexRoute,
  ExtIndexRoute: ExtIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
